apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-app
  template:
    metadata:
      labels:
        run: demo-app
    spec:
      initContainers:
      - name: demo-liquibase
        image: gcr.io/aaron-spring-gcp-demo/demo-liquibase
      containers:
      - name: demo-app
        image: gcr.io/aaron-spring-gcp-demo/jib-demo:latest
        ports:
        - containerPort: 8080
